### PR TITLE
Add Windows and Python 3 support

### PR DESCRIPTION
**Pull request by multippt**
This change-set adds Python 3 support as well as basic Windows support.

To build on Windows the following steps can be taken:
1. Install MSVC compiler (2008 for Python 2, 2015+ for Python 3)
2. Run pip install or python setup.py build to build the extension

Limitations:
* Max number of process workers is 1 on Windows at this time

### CODE REVIEW

**Comment by momyc** [comment]
Please update README.rst accordingly (don't forget to add yourself to the contributors list).
Thank you for contributing and using gevent-fastcgi. I haven't been maintaining it properly since I thought nobody including myself was actually using it.

**Comment by multippt** [comment]
Changeset rebased and readme updated.

**Comment by leohowell** [comment]
@momyc please accept this pr

**Comment by momyc** [comment]
I'm sorry for holding this back for so long. My current job... sucks. I was too busy solving imaginary problems. Thank you for doing all that work.

**Pull request merged**
